// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateMatchCompletionResult int32

const (
	CreateMatchCompletionResult_createMatchCompletionResultUnknownInternalFailure        CreateMatchCompletionResult = 0
	CreateMatchCompletionResult_createMatchCompletionResultSucceeded                     CreateMatchCompletionResult = 1
	CreateMatchCompletionResult_createMatchCompletionResultUnknownClientFailure          CreateMatchCompletionResult = -100
	CreateMatchCompletionResult_createMatchCompletionResultAlreadyInMatchOfSpecifiedType CreateMatchCompletionResult = -99
	CreateMatchCompletionResult_createMatchCompletionResultAlreadyCreatingMatch          CreateMatchCompletionResult = -98
	CreateMatchCompletionResult_createMatchCompletionResultAlreadyInMatch                CreateMatchCompletionResult = -97
	CreateMatchCompletionResult_createMatchCompletionResultFailedToCreateMucRoom         CreateMatchCompletionResult = -96
	CreateMatchCompletionResult_createMatchCompletionResultNoResponse                    CreateMatchCompletionResult = -95
	CreateMatchCompletionResult_createMatchCompletionResultLoggedOut                     CreateMatchCompletionResult = -94
)

var CreateMatchCompletionResult_name = map[int32]string{
	0:    "createMatchCompletionResultUnknownInternalFailure",
	1:    "createMatchCompletionResultSucceeded",
	-100: "createMatchCompletionResultUnknownClientFailure",
	-99:  "createMatchCompletionResultAlreadyInMatchOfSpecifiedType",
	-98:  "createMatchCompletionResultAlreadyCreatingMatch",
	-97:  "createMatchCompletionResultAlreadyInMatch",
	-96:  "createMatchCompletionResultFailedToCreateMucRoom",
	-95:  "createMatchCompletionResultNoResponse",
	-94:  "createMatchCompletionResultLoggedOut",
}

var CreateMatchCompletionResult_value = map[string]int32{
	"createMatchCompletionResultUnknownInternalFailure":        0,
	"createMatchCompletionResultSucceeded":                     1,
	"createMatchCompletionResultUnknownClientFailure":          -100,
	"createMatchCompletionResultAlreadyInMatchOfSpecifiedType": -99,
	"createMatchCompletionResultAlreadyCreatingMatch":          -98,
	"createMatchCompletionResultAlreadyInMatch":                -97,
	"createMatchCompletionResultFailedToCreateMucRoom":         -96,
	"createMatchCompletionResultNoResponse":                    -95,
	"createMatchCompletionResultLoggedOut":                     -94,
}

func (x CreateMatchCompletionResult) String() string {
	return proto.EnumName(CreateMatchCompletionResult_name, int32(x))
}

func (CreateMatchCompletionResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

type CreateMatchRequest struct {
	MatchType            string              `protobuf:"bytes,1,opt,name=match_type,json=matchType,proto3" json:"match_type,omitempty"`
	Seed                 int64               `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
	Configuration        *MatchConfiguration `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateMatchRequest) Reset()         { *m = CreateMatchRequest{} }
func (m *CreateMatchRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMatchRequest) ProtoMessage()    {}
func (*CreateMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *CreateMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMatchRequest.Unmarshal(m, b)
}
func (m *CreateMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMatchRequest.Marshal(b, m, deterministic)
}
func (m *CreateMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMatchRequest.Merge(m, src)
}
func (m *CreateMatchRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMatchRequest.Size(m)
}
func (m *CreateMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMatchRequest proto.InternalMessageInfo

func (m *CreateMatchRequest) GetMatchType() string {
	if m != nil {
		return m.MatchType
	}
	return ""
}

func (m *CreateMatchRequest) GetSeed() int64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *CreateMatchRequest) GetConfiguration() *MatchConfiguration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

type CreateMatchResponse struct {
	MatchId              string                      `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Result               CreateMatchCompletionResult `protobuf:"varint,2,opt,name=result,proto3,enum=niwrad.rpc.CreateMatchCompletionResult" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CreateMatchResponse) Reset()         { *m = CreateMatchResponse{} }
func (m *CreateMatchResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMatchResponse) ProtoMessage()    {}
func (*CreateMatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *CreateMatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMatchResponse.Unmarshal(m, b)
}
func (m *CreateMatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMatchResponse.Marshal(b, m, deterministic)
}
func (m *CreateMatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMatchResponse.Merge(m, src)
}
func (m *CreateMatchResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMatchResponse.Size(m)
}
func (m *CreateMatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMatchResponse proto.InternalMessageInfo

func (m *CreateMatchResponse) GetMatchId() string {
	if m != nil {
		return m.MatchId
	}
	return ""
}

func (m *CreateMatchResponse) GetResult() CreateMatchCompletionResult {
	if m != nil {
		return m.Result
	}
	return CreateMatchCompletionResult_createMatchCompletionResultUnknownInternalFailure
}

type MatchConfiguration struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchConfiguration) Reset()         { *m = MatchConfiguration{} }
func (m *MatchConfiguration) String() string { return proto.CompactTextString(m) }
func (*MatchConfiguration) ProtoMessage()    {}
func (*MatchConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *MatchConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchConfiguration.Unmarshal(m, b)
}
func (m *MatchConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchConfiguration.Marshal(b, m, deterministic)
}
func (m *MatchConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchConfiguration.Merge(m, src)
}
func (m *MatchConfiguration) XXX_Size() int {
	return xxx_messageInfo_MatchConfiguration.Size(m)
}
func (m *MatchConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_MatchConfiguration proto.InternalMessageInfo

type RunServerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunServerRequest) Reset()         { *m = RunServerRequest{} }
func (m *RunServerRequest) String() string { return proto.CompactTextString(m) }
func (*RunServerRequest) ProtoMessage()    {}
func (*RunServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *RunServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunServerRequest.Unmarshal(m, b)
}
func (m *RunServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunServerRequest.Marshal(b, m, deterministic)
}
func (m *RunServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunServerRequest.Merge(m, src)
}
func (m *RunServerRequest) XXX_Size() int {
	return xxx_messageInfo_RunServerRequest.Size(m)
}
func (m *RunServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunServerRequest proto.InternalMessageInfo

type RunServerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunServerResponse) Reset()         { *m = RunServerResponse{} }
func (m *RunServerResponse) String() string { return proto.CompactTextString(m) }
func (*RunServerResponse) ProtoMessage()    {}
func (*RunServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *RunServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunServerResponse.Unmarshal(m, b)
}
func (m *RunServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunServerResponse.Marshal(b, m, deterministic)
}
func (m *RunServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunServerResponse.Merge(m, src)
}
func (m *RunServerResponse) XXX_Size() int {
	return xxx_messageInfo_RunServerResponse.Size(m)
}
func (m *RunServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunServerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("niwrad.rpc.CreateMatchCompletionResult", CreateMatchCompletionResult_name, CreateMatchCompletionResult_value)
	proto.RegisterType((*CreateMatchRequest)(nil), "niwrad.rpc.CreateMatchRequest")
	proto.RegisterType((*CreateMatchResponse)(nil), "niwrad.rpc.CreateMatchResponse")
	proto.RegisterType((*MatchConfiguration)(nil), "niwrad.rpc.MatchConfiguration")
	proto.RegisterType((*RunServerRequest)(nil), "niwrad.rpc.RunServerRequest")
	proto.RegisterType((*RunServerResponse)(nil), "niwrad.rpc.RunServerResponse")
}

func init() {
	proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1)
}

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xd1, 0x8a, 0xd4, 0x30,
	0x14, 0x86, 0xed, 0xee, 0xb2, 0xe3, 0x1c, 0x51, 0x62, 0xc6, 0x8b, 0x11, 0x51, 0x86, 0xa2, 0x58,
	0xbd, 0xa8, 0xee, 0x88, 0x22, 0xa8, 0x88, 0x56, 0x85, 0x01, 0xdd, 0x85, 0xcc, 0x7a, 0xe3, 0x8d,
	0xd4, 0xe4, 0x4c, 0x0d, 0x76, 0x92, 0x6c, 0x9a, 0xb8, 0xcc, 0x43, 0xf8, 0x06, 0xea, 0xaa, 0x97,
	0xbe, 0xa4, 0x32, 0xd9, 0x8e, 0xed, 0x20, 0xd6, 0xed, 0x55, 0x93, 0x9c, 0xef, 0xff, 0xff, 0x9e,
	0xd3, 0x40, 0xdf, 0x1a, 0x9e, 0x1a, 0xab, 0x9d, 0xa6, 0xa0, 0xe4, 0xa1, 0xcd, 0x45, 0x6a, 0x0d,
	0x8f, 0x3f, 0x45, 0x40, 0x33, 0x8b, 0xb9, 0xc3, 0x57, 0xb9, 0xe3, 0xef, 0x19, 0x1e, 0x78, 0xac,
	0x1c, 0xbd, 0x0c, 0x30, 0x5f, 0xae, 0xdf, 0xba, 0x85, 0xc1, 0x61, 0x34, 0x8a, 0x92, 0x3e, 0xeb,
	0x87, 0x9d, 0xfd, 0x85, 0x41, 0x4a, 0x61, 0xab, 0x42, 0x14, 0xc3, 0x8d, 0x51, 0x94, 0x6c, 0xb2,
	0xf0, 0x4e, 0x9f, 0xc1, 0x59, 0xae, 0xd5, 0x4c, 0x16, 0xde, 0xe6, 0x4e, 0x6a, 0x35, 0xdc, 0x1c,
	0x45, 0xc9, 0x99, 0xf1, 0x95, 0xb4, 0x71, 0x4b, 0x83, 0x47, 0xd6, 0xae, 0x62, 0xeb, 0x50, 0x7c,
	0x00, 0x83, 0xb5, 0x38, 0x95, 0xd1, 0xaa, 0x42, 0x7a, 0x11, 0x4e, 0x1f, 0xe7, 0x91, 0xa2, 0x4e,
	0xd3, 0x0b, 0xeb, 0x89, 0xa0, 0x8f, 0x61, 0xdb, 0x62, 0xe5, 0x4b, 0x17, 0xd2, 0x9c, 0x1b, 0x5f,
	0x6f, 0x1b, 0xb6, 0xb4, 0x32, 0x3d, 0x37, 0x25, 0x06, 0xcf, 0x50, 0xce, 0x6a, 0x2c, 0xbe, 0x00,
	0xf4, 0xef, 0x5c, 0x31, 0x05, 0xc2, 0xbc, 0x9a, 0xa2, 0xfd, 0x88, 0xb6, 0xee, 0x4a, 0x3c, 0x80,
	0xf3, 0xad, 0xbd, 0xe3, 0x68, 0x37, 0x8f, 0xb6, 0xe0, 0x52, 0x87, 0x0d, 0xbd, 0x0b, 0x3b, 0xfc,
	0xdf, 0xc7, 0xaf, 0xd5, 0x07, 0xa5, 0x0f, 0xd5, 0x44, 0x39, 0xb4, 0x2a, 0x2f, 0x5f, 0xe4, 0xb2,
	0xf4, 0x16, 0xc9, 0x29, 0x9a, 0xc0, 0xd5, 0x0e, 0x6c, 0xea, 0x39, 0x47, 0x14, 0x28, 0x48, 0x44,
	0x1f, 0xc2, 0xad, 0xff, 0x1b, 0x64, 0xa5, 0x44, 0xe5, 0x56, 0xf2, 0x9f, 0x7f, 0xd5, 0x4f, 0x44,
	0x9f, 0xc3, 0xfd, 0x0e, 0xfa, 0x49, 0x69, 0x31, 0x17, 0x8b, 0x89, 0x0a, 0xa7, 0x7b, 0xb3, 0xa9,
	0x41, 0x2e, 0x67, 0x12, 0xc5, 0xf2, 0x37, 0x20, 0x5f, 0x1a, 0x99, 0xee, 0x10, 0xb5, 0x4c, 0x68,
	0x93, 0x54, 0x45, 0xa8, 0x21, 0x5f, 0x1b, 0xfa, 0x1e, 0xdc, 0x38, 0x71, 0x08, 0x72, 0xd4, 0x70,
	0x8f, 0xe0, 0x76, 0x07, 0xb7, 0xfc, 0x5a, 0x14, 0xfb, 0xba, 0x9e, 0x8e, 0xe7, 0x4c, 0xeb, 0x39,
	0xf9, 0xd6, 0xe0, 0x63, 0xb8, 0xd6, 0x81, 0xef, 0xea, 0xd5, 0x8c, 0xc9, 0xf7, 0x86, 0xd9, 0xe9,
	0x9c, 0xcb, 0x4b, 0x5d, 0x14, 0x28, 0xf6, 0xbc, 0x23, 0x3f, 0xfe, 0x20, 0x4f, 0x07, 0x6f, 0x7a,
	0xd6, 0xf0, 0x07, 0xd6, 0xf0, 0x9f, 0x1b, 0xbd, 0x5d, 0x74, 0x29, 0x33, 0xfc, 0xdd, 0x76, 0xb8,
	0x8b, 0x77, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xa5, 0xb1, 0xba, 0x98, 0x03, 0x00, 0x00,
}
