apiVersion: v1
kind: Service
metadata:
  name: {{ include "niwrad.fullname" . }}
  labels:
    {{- include "niwrad.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nakama.service.type }}
  ports:
  - name: "7349"
    port: 7349
    targetPort: 7349
  - name: api
    port: {{ .Values.nakama.service.portApi }}
    targetPort: {{ .Values.nakama.service.portApi }}
    nodePort: {{ .Values.nakama.service.nodePort }}
  - name: "7351"
    port: 7351
    targetPort: 7351
  selector:
    {{- include "niwrad.selectorLabels" . | nindent 4 }}
  externalIPs:
    {{- with .Values.externalIPs }}
      {{- range . }}
        - {{ . | quote }}
      {{- end }}
    {{- end }}