apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
{{- if not .Values.nakama.autoscaling.enabled }}
  replicas: {{ .Values.nakama.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Chart.Name }}
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Chart.Name }}
    spec:
      containers:
      - command:
        - /bin/sh
        - -ecx
        - |
          /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
           exec /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257
        image: {{ .Values.nakama.image.repository }} # TODO: ^can nakama even reach the db in other pod ?
        imagePullPolicy: {{ .Values.nakama.image.pullPolicy }}
        volumeMounts:
          - name: config-volume
            mountPath: /backend/build/nakama-config.yml
            subPath: nakama-config.yml
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:{{ .Values.service.portApi }}/
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 5
        name: game-backend
        ports:
        - containerPort: 7349
        - containerPort: {{ .Values.service.portApi }}
        - containerPort: 7351
        resources: {}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-configmap
      restartPolicy: Always
      serviceAccountName: "default"
status: {}
