apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "niwrad.fullname" . }}
  labels:
    {{- include "niwrad.labels" . | nindent 4 }}
spec:
{{- if not .Values.nakama.autoscaling.enabled }}
  replicas: {{ .Values.nakama.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "niwrad.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "niwrad.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - command:
        - /bin/sh
        - -ecx
        - |
          /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
           exec /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257
        image: {{ .Values.nakama.image.repository }}:{{ .Values.nakama.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.nakama.image.pullPolicy }}
        volumeMounts:
          - name: config-volume
            mountPath: /backend/build/nakama-config.yml
            subPath: nakama-config.yml
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:{{ .Values.nakama.service.portApi }}/
          failureThreshold: 5
          periodSeconds: 10
          timeoutSeconds: 5
        name: game-backend
        ports:
        - containerPort: 7349
        - containerPort: {{ .Values.nakama.service.portApi }}
        - containerPort: 7351
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-configmap
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
status: {}
