apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.nakama.service.type }}
  ports:
  - name: "7349"
    port: 7349
    targetPort: 7349
  - name: api
    port: {{ .Values.nakama.service.portApi }}
    targetPort: {{ .Values.nakama.service.portApi }}
  - name: "7351"
    port: 7351
    targetPort: 7351
  selector:
    io.kompose.service: {{ .Chart.Name }}
  

