// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateMatchCompletionResult int32

const (
	CreateMatchCompletionResult_createMatchCompletionResultUnknownInternalFailure        CreateMatchCompletionResult = 0
	CreateMatchCompletionResult_createMatchCompletionResultSucceeded                     CreateMatchCompletionResult = 1
	CreateMatchCompletionResult_createMatchCompletionResultUnknownClientFailure          CreateMatchCompletionResult = -100
	CreateMatchCompletionResult_createMatchCompletionResultAlreadyInMatchOfSpecifiedType CreateMatchCompletionResult = -99
	CreateMatchCompletionResult_createMatchCompletionResultAlreadyCreatingMatch          CreateMatchCompletionResult = -98
	CreateMatchCompletionResult_createMatchCompletionResultAlreadyInMatch                CreateMatchCompletionResult = -97
	CreateMatchCompletionResult_createMatchCompletionResultFailedToCreateMucRoom         CreateMatchCompletionResult = -96
	CreateMatchCompletionResult_createMatchCompletionResultNoResponse                    CreateMatchCompletionResult = -95
	CreateMatchCompletionResult_createMatchCompletionResultLoggedOut                     CreateMatchCompletionResult = -94
)

var CreateMatchCompletionResult_name = map[int32]string{
	0:    "createMatchCompletionResultUnknownInternalFailure",
	1:    "createMatchCompletionResultSucceeded",
	-100: "createMatchCompletionResultUnknownClientFailure",
	-99:  "createMatchCompletionResultAlreadyInMatchOfSpecifiedType",
	-98:  "createMatchCompletionResultAlreadyCreatingMatch",
	-97:  "createMatchCompletionResultAlreadyInMatch",
	-96:  "createMatchCompletionResultFailedToCreateMucRoom",
	-95:  "createMatchCompletionResultNoResponse",
	-94:  "createMatchCompletionResultLoggedOut",
}

var CreateMatchCompletionResult_value = map[string]int32{
	"createMatchCompletionResultUnknownInternalFailure":        0,
	"createMatchCompletionResultSucceeded":                     1,
	"createMatchCompletionResultUnknownClientFailure":          -100,
	"createMatchCompletionResultAlreadyInMatchOfSpecifiedType": -99,
	"createMatchCompletionResultAlreadyCreatingMatch":          -98,
	"createMatchCompletionResultAlreadyInMatch":                -97,
	"createMatchCompletionResultFailedToCreateMucRoom":         -96,
	"createMatchCompletionResultNoResponse":                    -95,
	"createMatchCompletionResultLoggedOut":                     -94,
}

func (x CreateMatchCompletionResult) String() string {
	return proto.EnumName(CreateMatchCompletionResult_name, int32(x))
}

func (CreateMatchCompletionResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

type StopMatchCompletionResult int32

const (
	StopMatchCompletionResult_stopServerCompletionResultUnknownInternalFailure StopMatchCompletionResult = 0
	StopMatchCompletionResult_stopServerCompletionResultSucceeded              StopMatchCompletionResult = 1
)

var StopMatchCompletionResult_name = map[int32]string{
	0: "stopServerCompletionResultUnknownInternalFailure",
	1: "stopServerCompletionResultSucceeded",
}

var StopMatchCompletionResult_value = map[string]int32{
	"stopServerCompletionResultUnknownInternalFailure": 0,
	"stopServerCompletionResultSucceeded":              1,
}

func (x StopMatchCompletionResult) String() string {
	return proto.EnumName(StopMatchCompletionResult_name, int32(x))
}

func (StopMatchCompletionResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

type CreateMatchRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMatchRequest) Reset()         { *m = CreateMatchRequest{} }
func (m *CreateMatchRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMatchRequest) ProtoMessage()    {}
func (*CreateMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *CreateMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMatchRequest.Unmarshal(m, b)
}
func (m *CreateMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMatchRequest.Marshal(b, m, deterministic)
}
func (m *CreateMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMatchRequest.Merge(m, src)
}
func (m *CreateMatchRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMatchRequest.Size(m)
}
func (m *CreateMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMatchRequest proto.InternalMessageInfo

type CreateMatchResponse struct {
	MatchId              string                      `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Result               CreateMatchCompletionResult `protobuf:"varint,2,opt,name=result,proto3,enum=nakama.niwrad.api.rpc.CreateMatchCompletionResult" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CreateMatchResponse) Reset()         { *m = CreateMatchResponse{} }
func (m *CreateMatchResponse) String() string { return proto.CompactTextString(m) }
func (*CreateMatchResponse) ProtoMessage()    {}
func (*CreateMatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *CreateMatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMatchResponse.Unmarshal(m, b)
}
func (m *CreateMatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMatchResponse.Marshal(b, m, deterministic)
}
func (m *CreateMatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMatchResponse.Merge(m, src)
}
func (m *CreateMatchResponse) XXX_Size() int {
	return xxx_messageInfo_CreateMatchResponse.Size(m)
}
func (m *CreateMatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMatchResponse proto.InternalMessageInfo

func (m *CreateMatchResponse) GetMatchId() string {
	if m != nil {
		return m.MatchId
	}
	return ""
}

func (m *CreateMatchResponse) GetResult() CreateMatchCompletionResult {
	if m != nil {
		return m.Result
	}
	return CreateMatchCompletionResult_createMatchCompletionResultUnknownInternalFailure
}

type StopMatchRequest struct {
	MatchId              string   `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopMatchRequest) Reset()         { *m = StopMatchRequest{} }
func (m *StopMatchRequest) String() string { return proto.CompactTextString(m) }
func (*StopMatchRequest) ProtoMessage()    {}
func (*StopMatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *StopMatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopMatchRequest.Unmarshal(m, b)
}
func (m *StopMatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopMatchRequest.Marshal(b, m, deterministic)
}
func (m *StopMatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopMatchRequest.Merge(m, src)
}
func (m *StopMatchRequest) XXX_Size() int {
	return xxx_messageInfo_StopMatchRequest.Size(m)
}
func (m *StopMatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopMatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopMatchRequest proto.InternalMessageInfo

func (m *StopMatchRequest) GetMatchId() string {
	if m != nil {
		return m.MatchId
	}
	return ""
}

type StopMatchResponse struct {
	Result               StopMatchCompletionResult `protobuf:"varint,1,opt,name=result,proto3,enum=nakama.niwrad.api.rpc.StopMatchCompletionResult" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *StopMatchResponse) Reset()         { *m = StopMatchResponse{} }
func (m *StopMatchResponse) String() string { return proto.CompactTextString(m) }
func (*StopMatchResponse) ProtoMessage()    {}
func (*StopMatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *StopMatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopMatchResponse.Unmarshal(m, b)
}
func (m *StopMatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopMatchResponse.Marshal(b, m, deterministic)
}
func (m *StopMatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopMatchResponse.Merge(m, src)
}
func (m *StopMatchResponse) XXX_Size() int {
	return xxx_messageInfo_StopMatchResponse.Size(m)
}
func (m *StopMatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopMatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopMatchResponse proto.InternalMessageInfo

func (m *StopMatchResponse) GetResult() StopMatchCompletionResult {
	if m != nil {
		return m.Result
	}
	return StopMatchCompletionResult_stopServerCompletionResultUnknownInternalFailure
}

type User struct {
	MatchesOwned         []string `protobuf:"bytes,1,rep,name=matches_owned,json=matchesOwned,proto3" json:"matches_owned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetMatchesOwned() []string {
	if m != nil {
		return m.MatchesOwned
	}
	return nil
}

type UnityServer struct {
	MatchId              string   `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnityServer) Reset()         { *m = UnityServer{} }
func (m *UnityServer) String() string { return proto.CompactTextString(m) }
func (*UnityServer) ProtoMessage()    {}
func (*UnityServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *UnityServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnityServer.Unmarshal(m, b)
}
func (m *UnityServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnityServer.Marshal(b, m, deterministic)
}
func (m *UnityServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnityServer.Merge(m, src)
}
func (m *UnityServer) XXX_Size() int {
	return xxx_messageInfo_UnityServer.Size(m)
}
func (m *UnityServer) XXX_DiscardUnknown() {
	xxx_messageInfo_UnityServer.DiscardUnknown(m)
}

var xxx_messageInfo_UnityServer proto.InternalMessageInfo

func (m *UnityServer) GetMatchId() string {
	if m != nil {
		return m.MatchId
	}
	return ""
}

func init() {
	proto.RegisterEnum("nakama.niwrad.api.rpc.CreateMatchCompletionResult", CreateMatchCompletionResult_name, CreateMatchCompletionResult_value)
	proto.RegisterEnum("nakama.niwrad.api.rpc.StopMatchCompletionResult", StopMatchCompletionResult_name, StopMatchCompletionResult_value)
	proto.RegisterType((*CreateMatchRequest)(nil), "nakama.niwrad.api.rpc.CreateMatchRequest")
	proto.RegisterType((*CreateMatchResponse)(nil), "nakama.niwrad.api.rpc.CreateMatchResponse")
	proto.RegisterType((*StopMatchRequest)(nil), "nakama.niwrad.api.rpc.StopMatchRequest")
	proto.RegisterType((*StopMatchResponse)(nil), "nakama.niwrad.api.rpc.StopMatchResponse")
	proto.RegisterType((*User)(nil), "nakama.niwrad.api.rpc.User")
	proto.RegisterType((*UnityServer)(nil), "nakama.niwrad.api.rpc.UnityServer")
}

func init() {
	proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1)
}

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0x80, 0xdf, 0xec, 0x9d, 0x36, 0x7a, 0xf8, 0x90, 0x31, 0x20, 0xad, 0xe2, 0x66, 0xca, 0x98,
	0x08, 0x43, 0xa4, 0x5d, 0xf9, 0x10, 0x12, 0x70, 0x31, 0x2a, 0x10, 0x45, 0x40, 0xa5, 0x74, 0xbd,
	0x41, 0x42, 0x93, 0xb1, 0xcf, 0x8a, 0xb5, 0xd4, 0x36, 0x8e, 0x43, 0x55, 0xc4, 0x4f, 0x01, 0x06,
	0x5c, 0xf2, 0x27, 0x41, 0x4d, 0xb3, 0xa6, 0x48, 0xc4, 0x2c, 0x77, 0x39, 0xf6, 0x73, 0xce, 0x13,
	0xfb, 0x9c, 0x40, 0xc3, 0x1a, 0x1e, 0x1b, 0xab, 0x9d, 0xa6, 0x57, 0x14, 0x3b, 0x62, 0x63, 0x16,
	0x2b, 0x39, 0xb1, 0x4c, 0xc4, 0xcc, 0xc8, 0xd8, 0x1a, 0x1e, 0x5e, 0x06, 0xda, 0xb5, 0xc8, 0x1c,
	0xbe, 0x64, 0x8e, 0xbf, 0x4b, 0xf0, 0x7d, 0x8e, 0x99, 0x0b, 0x3f, 0xc1, 0xa5, 0x3f, 0xa2, 0x99,
	0xd1, 0x2a, 0x43, 0xda, 0x84, 0x33, 0xe3, 0x59, 0xe0, 0x40, 0x8a, 0x8d, 0x60, 0x33, 0x88, 0x1a,
	0xc9, 0x7a, 0xf1, 0xde, 0x13, 0xf4, 0x39, 0xac, 0x59, 0xcc, 0xf2, 0xd4, 0x6d, 0xac, 0x6c, 0x06,
	0xd1, 0x85, 0x4e, 0x27, 0xfe, 0x6b, 0xbd, 0x78, 0x29, 0x6d, 0x57, 0x8f, 0x4d, 0x8a, 0x4e, 0x6a,
	0x95, 0x14, 0x64, 0x52, 0x66, 0x08, 0x6f, 0x01, 0x19, 0x38, 0x6d, 0x96, 0x8d, 0x3c, 0xa5, 0xc3,
	0x37, 0x70, 0x71, 0x69, 0x7b, 0xa9, 0xfa, 0x6c, 0xe1, 0x13, 0x14, 0x3e, 0xed, 0x1a, 0x9f, 0x05,
	0x59, 0x6b, 0x73, 0x13, 0x56, 0x87, 0x19, 0x5a, 0xba, 0x05, 0xe7, 0x8b, 0x8a, 0x98, 0x1d, 0xe8,
	0x89, 0xc2, 0x99, 0xc6, 0xff, 0x51, 0x23, 0x39, 0x57, 0x06, 0xfb, 0xb3, 0x58, 0x18, 0xc1, 0xd9,
	0xa1, 0x92, 0x6e, 0x3a, 0x40, 0xfb, 0x01, 0xad, 0xc7, 0x7a, 0xe7, 0x78, 0x15, 0xae, 0x7a, 0x0e,
	0x83, 0xde, 0x85, 0x5d, 0x5e, 0xbf, 0x3c, 0x54, 0x47, 0x4a, 0x4f, 0x54, 0x4f, 0x39, 0xb4, 0x8a,
	0xa5, 0x4f, 0x99, 0x4c, 0x73, 0x8b, 0xe4, 0x3f, 0x1a, 0xc1, 0x35, 0x0f, 0x36, 0xc8, 0x39, 0x47,
	0x14, 0x28, 0x48, 0x40, 0x1f, 0x42, 0xeb, 0xdf, 0x05, 0xba, 0xa9, 0x44, 0xe5, 0x4e, 0xd2, 0x7f,
	0xfe, 0x55, 0x3e, 0x01, 0x7d, 0x02, 0xf7, 0x3d, 0xf4, 0x5e, 0x6a, 0x91, 0x89, 0x69, 0x4f, 0x15,
	0xab, 0xfd, 0xc3, 0x81, 0x41, 0x2e, 0x0f, 0x25, 0x8a, 0xfd, 0xa9, 0x41, 0xf2, 0xa5, 0x4a, 0xe3,
	0x97, 0x28, 0xd3, 0x14, 0xc7, 0x24, 0xd5, 0xa8, 0xd8, 0x43, 0xbe, 0x56, 0xf4, 0x3d, 0xb8, 0x71,
	0x6a, 0x09, 0x72, 0x5c, 0x71, 0x8f, 0xa0, 0xed, 0xe1, 0x66, 0x5f, 0x8b, 0x62, 0x5f, 0x97, 0xb7,
	0x93, 0xf3, 0x44, 0xeb, 0x31, 0xf9, 0x56, 0xe1, 0x1d, 0xd8, 0xf6, 0xe0, 0xaf, 0xf4, 0x49, 0x13,
	0x92, 0xef, 0x15, 0xb3, 0xeb, 0xbd, 0x97, 0x17, 0x7a, 0x34, 0x42, 0xd1, 0xcf, 0x1d, 0xf9, 0xb1,
	0x40, 0x76, 0x3e, 0x42, 0xb3, 0xb6, 0x3b, 0xe9, 0x1d, 0x68, 0x67, 0x4e, 0x9b, 0x79, 0x9f, 0x9d,
	0xba, 0x3b, 0xae, 0xc3, 0x56, 0x3d, 0xb5, 0xd4, 0x1c, 0x8f, 0xb7, 0x5f, 0x37, 0xe7, 0xf3, 0xd2,
	0x9a, 0xcf, 0x4b, 0x8b, 0x19, 0xd9, 0xb2, 0x86, 0x3f, 0xb0, 0x86, 0xff, 0x5c, 0x59, 0xdf, 0x33,
	0x32, 0x4e, 0x0c, 0x7f, 0xbb, 0x56, 0xfc, 0x5b, 0x6e, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xfd,
	0x29, 0xa6, 0x5f, 0x68, 0x04, 0x00, 0x00,
}
