unity:
  replicaCount: 0

  image:
    repository: louis030195/executor
    pullPolicy: IfNotPresent

nakama:
  replicaCount: 1

  image:
    repository: louis030195/nakama
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    portApi: 7350

  default:
    username: azerty@azerty.com
    password: azertyazerty


  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  
js:
  replicaCount: 0

  image:
    repository: louis030195/niwrad-js
    pullPolicy: Never

test:
  image:
    repository: louis030195/integration
    pullPolicy: Always
