name: Acquire activation file manually

# Maybe could check if license exist then do or not
on:
  workflow_dispatch:
    inputs:
      unityVersion:
        description: 'Unity version'
        required: true
        default: 2020.2.0f1
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: webbertakken/unity-request-manual-activation-file@v2.0-alpha-1
        with:
          unityVersion: ${{ github.event.inputs.unityVersion }}
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
      # Then download the artifact & go here https://license.unity3d.com/manual

        