name: Release manually

# Maybe could check if license exist then do or not
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Which commit to release'
        required: true
      release:
        description: 'Release name'
        required: true
      tag:
        description: 'Release tag'
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          commit: ${{ github.event.inputs.commit }}
      
      - name: Display structure of downloaded files
        run: ls offline-clients

      - name: Zip every artifacts
        run: |
          cd offline-clients
          for file in $(ls -I "*.zip"); do zip -r "${file}.zip" "$file"; done

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.release }}
          draft: false
          prerelease: false

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: offline-clients/*.zip
          tag: ${{ github.event.inputs.tag }}
          overwrite: true
          file_glob: true
